### PR TITLE
WebView Replaced with Sticky Header List View & Material Dialog

### PR DESCRIPTION
**Pull request by ahornerr**
Hello cketti,

I've modified the changelog library to use the MaterialDialog library, and switched the WebView out for a StickyHeaderListView (See the screenshot in my readme). You may want to modify some of my code to allow for customization (for example, being able to supply a custom sticky header view or a custom list item view).

### CODE REVIEW

**Comment by cketti** [comment]
@ahornerr: Sorry for taking this long to respond. Thank you for the pull request!
However, my plans for this library go into an opposite direction. I want to remove all the UI code and create a core library that only contains the changelog resource logic. Then maybe a couple of libraries implementing different ways to present the data, e.g. using fragments or dialogs.

I'm keeping this pull request open to remind me to add your code to the sample project as one way to present the changelog.

**Comment by johnjohndoe** [comment]
> ... I want to remove all the UI code and create a core library that only contains the changelog resource logic ...

@cketti Any progress on this topic? :construction:

**Comment by cketti** [comment]
@johnjohndoe: Thanks for the reminder. I started work here: https://github.com/cketti/ckChangeLog/tree/version_2

Feel free to propose changes or submit pull requests against that branch.

**Comment by johnjohndoe** [comment]
@cketti Thank you for the hint. I will review your work soon.

**Comment by johnjohndoe** [comment]
@cketti What is the schedule for the release of version 2 of your library? I am looking forward to it. :hamster:

**Comment by cketti** [comment]
@johnjohndoe There's always something that seems to come up. If you'll be at the ART meetup this week there's a good chance we might be able to finish a release candidate.

**Comment by cketti** [comment]
Hopefully it will be easy to build this upon version 2.0.0's core artifact. Please check out #39.

**Pull request closed without merging**
